---
# tasks file for ansible-role-wireguard
- name: Wireguard | Ensure all directories exists
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: 0700
  with_items:
    - "{{ wireguard_path }}"
    - "{{ wireguard_path }}/config"

- name: Wireguard | Templating docker-compose.yml
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ wireguard_path }}/docker-compose.yml"
    mode: 0644

- name: Wireguard | Run Wireguard
  docker_compose:
    project_src: "{{ wireguard_path }}"
    state: present

- name: Wireguard | Wait until the file peer1.conf is present before continuing
  ansible.builtin.wait_for:
    path: "{{ wireguard_path }}/config/peer{{ wireguard_peers }}/peer{{ wireguard_peers }}.conf"

- name: Wireguard | fetch client config
  ansible.builtin.fetch:
    src: "{{ wireguard_path }}/config/peer{{ item }}/peer{{ item }}.conf"
    dest: "{{ playbook_dir }}/wireguard/config/{{ inventory_hostname }}-peer{{ item }}.conf"
    flat: true
  loop: "{{ range(1, wireguard_peers + 1) | list }}"
